/* Generated by branding/build-space-css.js — edit that file, not this one.
 * Picks one of the 8 new-chat greetings for this page load, never the same one twice in a
 * row, and exposes it as <html data-greeting> for space.css. */
(function () {
  var COUNT = 8;
  var KEY = 'cmubs-greeting';
  var pick = Math.floor(Math.random() * COUNT);
  try {
    var last = sessionStorage.getItem(KEY);
    if (COUNT > 1 && String(pick) === last) {
      pick = (pick + 1 + Math.floor(Math.random() * (COUNT - 1))) % COUNT;
    }
    sessionStorage.setItem(KEY, String(pick));
  } catch (e) {
    /* Storage blocked: a plain random pick is fine. */
  }
  document.documentElement.setAttribute('data-greeting', String(pick));
})();
